### ISSUE TITLE
External Connections?

### ISSUE THREAD

**Issue by sidot3291** [heroku/heroku-buildpack-pgbouncer#111]
It it possible to use pgbouncer on Heroku and still accept external connections?

For example, expose this for external connections:
postgres://user:pass@my-pgbouncer.herokuapp.com:6000/dbname

**Comment by binarycleric** [comment]
@sidot3291 Not with the buildpack. It only opens a local connection that processes on the dyno can use. We have a public beta of [on-server pgbouncer](https://devcenter.heroku.com/articles/postgres-connection-pooling) but don't have a timeline on GA yet.
