### ISSUE TITLE
Some Environment Variables not being detected from dyno's app settings

### ISSUE THREAD

**Issue by kand617** [heroku/heroku-buildpack-pgbouncer#120]
I seem to facing some strange issues with PG Bouncer where some of the variables that I use in my Heorku app are not reflected on console of PG Bouncer. 

Build Pack Details:
```
https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/pgbouncer.tgz
heroku/nodejs
```

Proc File:

```
web: bin/start-pgbouncer-stunnel node server/server.js

```

App Config:

![image](https://user-images.githubusercontent.com/5092518/54251220-84a4c780-4581-11e9-9def-e9994c0550d4.png)
Note the default pool size is : `PGBOUNCER_DEFAULT_POOL_SIZE = 350`

PG Bouncer CLI Config:

![image](https://user-images.githubusercontent.com/5092518/54251283-b027b200-4581-11e9-9d6d-fc33ed0508d4.png)

However the CLI shows `default_pool_size = 250`

**Comment by mble** [comment]
Hey @kand617 👋,

When you're connecting to the PgBouncer admin database, that looks much more like the settings for the PgBouncer instance used as part of Connection Pooling (ref: https://devcenter.heroku.com/articles/postgres-connection-pooling). The two PgBouncer configurations are separate, with the configuration variables only affecting the buildpack configuration. Connection Pooling is not currently configurable.

**Comment by kand617** [comment]
So you are saying connection pooling can happen in two places. 

Method 1. At the database server : https://devcenter.heroku.com/articles/postgres-connection-pooling

Method 2: At the dyno level: Heroku pg bouncer build pack. 

Correct?
If so is there much benefit in using method 2 , if method 1 is used?
As you mentioned that the server connection pooling (method 1) is not configurable. 
Trying to change 250 to 400 on pgbouncer cli gave 
```
pgbouncer=# SET default_pool_size = 400;
ERROR:  admin access needed
```
How to use 500 connections if max is 250?

**Comment by mble** [comment]
@kand617 That's correct. As server level pooling isn't as configurable, there are still reasons to use the buildpack over Connection Pooling. You may need `statement` level pooling, for example.

We prevent maxing out the connections for the default pool size on the server side PgBouncer in order to allow for non-pooled connections, as well as multiple roles, as these require their own pools.

The feature is still in beta, and is subject to change in the future.
