### ISSUE TITLE
start-x as seperate implementation

### ISSUE THREAD

**Issue by mobilutz** [heroku/heroku-buildpack-pgbouncer#130]
I just stumbled over the `start-pgbouncer` script which is really awesome implemented.

I am very much thinking about doing a clamav/clamd implementation and then the though came up:
Why isn't the `start-x` script an external implementation which can be used in other buildpacks?

Did anyone think about extracting this, to allow easier use of the implementation without copy/paste everything?

I would like to help, but am not sure how to start this.

**Comment by beanieboi** [comment]
the `start-x` is a pattern we use a lot and usually those scripts don't change a lot. By having them separate we don't create dependencies between buildpacks which allows us to move buildpacks independently. feel free to copy from existing buildpacks, thats what they are for :)
