### ISSUE TITLE
Update to PgBouncer 1.12.x

### ISSUE THREAD

**Issue by ndastur** [heroku/heroku-buildpack-pgbouncer#131]
Is there any chance of an update to 1.12.x
The version in this buildpack is really quite old now I'm not sure if that's why I can't connect to my PG server. It issues a SSL error
https://github.com/pgbouncer/pgbouncer/blob/master/NEWS.md

**Comment by edmorley** [comment]
@ndastur Hi! As of #132 the buildpack now uses pgbouncer 1.13 for Heroku-16 and newer :-)

**Comment by ndastur** [comment]
Perfect. Thank you
