### ISSUE TITLE
`heroku/pgbouncer` always expands to an s3 url for a tgz file

### ISSUE THREAD

**Issue by mmrobins** [heroku/heroku-buildpack-pgbouncer#134]
Not a big deal for functionality, but when managing buildpacks with terraform it always shows a diff when using `heroku/pgbouncer` the buildpack since that ends up expanding to https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/pgbouncer.tgz.  It expands to that s3 url no matter how you add `heroku/pgbouncer`, using terraform, the cli tool, or the settings page in the web UI.  Not sure why it expands for this buildpack and not others

**Comment by edmorley** [comment]
@mmrobins Hi! This issue occurs for any buildpack when using the Buildpack Registry style short aliases - tracked at:
terraform-providers/terraform-provider-heroku/issues/170

Closing this out for now - would you mind pinging that other issue to remind the maintainers of the terraform provider that it's still an issue? :-)
