### ISSUE TITLE
Is there anyway to access admin console?

### ISSUE THREAD

**Issue by redreceipt** [heroku/heroku-buildpack-pgbouncer#163]
I'd just like to see basic stats and evidence that the buildpack is working? Trying this doesn't work...

```sh
heroku run bash -a <APP>
~ $ psql postgres://<DATABASEURL_USER>:< DATABASEURL_PW>@localhost:6000/pgbouncer
psql: error: connection to server at "localhost" (127.0.0.1), port 6000 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```

**Comment by mble-sfdc** [comment]
@redreceipt Apologies for the delay in responding to you on this. When running `run bash`, the pgbouncer isn't started. You'd need to use `run "bin/start-pgbouncer bash"` instead so the pgbouncer process is started.

Alternatively, consider using [Heroku Exec](https://devcenter.heroku.com/articles/exec) to connect to a running dyno where the process is already running.

The `pgbouncer` database can be accessed over the Unix port, so something like `psql -d pgbouncer -U pgbouncer -p 6000 -h /tmp` would work (see: #86).
