### ISSUE TITLE
bug? bin/start-pgbouncer in Procfile breaks "heroku local" 

### ISSUE THREAD

**Issue by bf4** [heroku/heroku-buildpack-pgbouncer#177]
I start my server locally with `heroku local`
To use this buildpack I need to edit my Procfile to add `bin/start-pgbouncer` 

```diff
- web: start_app
+ web: bin/start-pgbouncer start_app
```

but now heroku local fails (as expected, I suppose) with `/bin/sh: bin/start-pgbouncer: No such file or directory`

I haven't found how Heroku recommends working with both this buildpack and the heroku cli.  I can open a support ticket, but I figure this is an issue everyone might have?

**Comment by mble** [comment]
@bf4 `heroku local` doesn't attempt to run a full copy of your environment - it's pretty much "just" reading the Procfile and using [foreman](https://www.npmjs.com/package/foreman) to wrangle it, so anything added by buildpacks etc is skipped entirely - there is no "build" step as there would be on Heroku.

If you need something local that is close to production, using a Docker image from the [heroku/stack-images](https://github.com/heroku/stack-images) repo as your base and going from there _can_ work, but requires a bit of work.

**Comment by bf4** [comment]
gotcha. I'd love to see an example of using one of those docker images for dev, test and prod. (We already sorta have this worked out, but I hadn't considered buildpacks).  But, that's off topic, so I'll close this and now there's an answer if anyone searches for this.
