### ISSUE TITLE
Update to 1.21.0

### ISSUE THREAD

**Issue by elkesrio** [heroku/heroku-buildpack-pgbouncer#182]
Hey,

Is there a way to use PgBouncer 1.21.0? It adds a very requested feature: using prepared statements on transaction mode

**Comment by kigster** [comment]
https://github.com/heroku/heroku-buildpack-pgbouncer/pull/185

**Comment by mble-sfdc** [comment]
We released https://github.com/heroku/heroku-buildpack-pgbouncer/releases/tag/v0.16.0 for 1.23.1.
