### ISSUE TITLE
Set prepared statements to false in after_fork for Unicorn

### ISSUE THREAD

**Issue by catsby** [heroku/heroku-buildpack-pgbouncer#19]
Sanity check here: the recommend setup in the [README here][1] uses an initializer, however the typically Unicorn setup will re-eaablish the connection in the `after_fork` block. Unless this line: 

```ruby
alias initialize_without_config_boolean_coercion initialize
``` 

does something I don't understand, I think Unicorn users will still be using prepared statements even with that initializer. 

[1]: https://github.com/gregburek/heroku-buildpack-pgbouncer#disable-prepared-statements

**Comment by gregburek** [comment]
It is possible, but I would expect the support volume from this to be much greater than it has been around mysterious prepared_statements when using unicorn. 

If you find this issue while trouble shooting this problem, please re-open with a +1 so that we may improve our docs and warn future users.
