### ISSUE TITLE
Remove support for Heroku-18

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-pgbouncer#190]
Heroku-18 is EOL, so can't be used by customers any more.

As such the Heroku-18 pgbouncer binary, CI matrix entry, `Makefile` target, and README mentions could be removed:
https://github.com/search?q=repo%3Aheroku%2Fheroku-buildpack-pgbouncer%2018&type=code

**Comment by brahyt-sf** [comment]
https://github.com/heroku/heroku-buildpack-pgbouncer/pull/191
