### ISSUE TITLE
buildback running unsecure version of stunnel and openSSL

### ISSUE THREAD

**Issue by edwardotis** [heroku/heroku-buildpack-pgbouncer#42]
Version v0.3.2 of the buildpack reports:

2014-12-17T22:06:21.049405+00:00 app[web.1]: 2014.12.17 22:06:21 LOG5[43]: stunnel 5.02 on x86_64-unknown-linux-gnu platform
2014-12-17T22:06:21.049417+00:00 app[web.1]: 2014.12.17 22:06:21 LOG5[43]: Compiled/running with OpenSSL 0.9.8k 25 Mar 2009

Please review stunnel changelog which reports 2 HIGH urgency updates since stunnel 5.02 was released, which include updates to openSSL
https://www.stunnel.org/sdf_ChangeLog.html

**Comment by gregburek** [comment]
I have released version `v0.3.3` of this buildpack but ran into some troubles. The proper openssl headers are not available on the `cedar` stack, so if you are on `cedar`, you will continue to get stunnel v5.02. I recommend upgrading as soon as possible to `cedar-14` to get `v5.08` and the latest builds. 

As stunnel on linux uses the system libraries, I recommend checking https://devcenter.heroku.com/articles/cedar-ubuntu-packages to see the applicable ubuntu packaged openssl versions.
