### ISSUE TITLE
question - pgbouncer and heroku HA/failover

### ISSUE THREAD

**Issue by soulware** [heroku/heroku-buildpack-pgbouncer#46]
Preface - not a criticism of the buildpack - just seeking for some clarity.

We just experienced a heroku HA/failover event last night.
I think we discovered (but hadn't previously considered) that the pgbouncer buildpack will not handle DATABASE_URL being updated. A restart of the dyno will not cause the buildpack to (re)generate `pgbouncer.ini`. The only way to resolve is to redeploy (and rebuild the buildpack).

Is this a reasonable understanding of the situation?

**Comment by gregburek** [comment]
As of e45e096dc2f6fd79c931cb4e10dc0925b0220a24, the buildpack renders config files upon dyno boot, not app build. The HA failover process involves pushing new credentials to your app, which triggers an app restart and will result in the config files being re-rendered. I would take a look at what version of this buildpack you are pinned to and see if it is possible to use the latest release, v0.3.3

**Comment by soulware** [comment]
Awesome. Thanks for the info.
