### ISSUE TITLE
ENABLE_STUNNEL_AMAZON_RDS_FIX instructions are incorrect

### ISSUE THREAD

**Issue by edwardotis** [heroku/heroku-buildpack-pgbouncer#49]
@gregburek 

Hi Greg,

In the following commit, you changed the code that processed the ENABLE_STUNNEL_AMAZON_RDS_FIX env variable, and you made the instructions on the README.md incorrect for this feature.

https://github.com/heroku/heroku-buildpack-pgbouncer/commit/a8ac77243dbc77698357406a56064dd7b491b1e2

I would recommend reverting your changes to lines 15 and 16 in order to make that part of the generation script correct again. It's the safer option. More detail in my comments on that commit.

Thanks,

Ed

**Comment by gregburek** [comment]
This is fixed in #55

**Comment by edwardotis** [comment]
Thanks!
