### ISSUE TITLE
Meaning of PGBOUNCER_DEFAULT_POOL_SIZE

### ISSUE THREAD

**Issue by davidmilo** [heroku/heroku-buildpack-pgbouncer#51]
I am confused with meaning of this variable.

Does this mean overall pool of available connections to database or is it available pool of connections per dyno?

**Comment by davidmilo** [comment]
Let's say I want to share 120 connections among 70 dynos each having 2 workers running with DB_POOL of 5

does that mean I should set
PGBOUNCER_MAX_CLIENT_CONN=1000 (70*2*5 =700)
PGBOUNCER_DEFAULT_POOL_SIZE=100 (I need 20 connections for other applications)

or should PGBOUNCER_DEFAULT_POOL_SIZE be set based on how big pool I want reserved for each dyno?

Also could you evaluate more on meaning of PGBOUNCER_RESERVE_POOL_SIZE?

**Comment by gregburek** [comment]
`PGBOUNCER_DEFAULT_POOL_SIZE` is the pool of connections per dyno. There is no coordination between dynos running pgbouncer locally, so overall limits are not possible. The config var is meant to directly relate to `default_pool_size` in the [rendered config file](https://github.com/heroku/heroku-buildpack-pgbouncer/blob/master/bin/gen-pgbouncer-conf.sh#L48) as documented at http://pgbouncer.projects.pgfoundry.org/doc/config.html 

`PGBOUNCER_MAX_CLIENT_CONN` limits the number of connections your app in the dyno establishes to pgbouncer, also running in the dyno. If you have 1000 connections from an app in one dyno, you probably have a connection leak. 

`PGBOUNCER_RESERVE_POOL_SIZE` is the number of connections that are spun up if queries are waiting in the pgbouncer queue for `PGBOUNCER_RESERVE_POOL_TIMEOUT` seconds. It is important to plan such that:

```
(PGBOUNCER_RESERVE_POOL_SIZE + PGBOUNCER_DEFAULT_POOL_SIZE) * number of dynos <= postgres max_connections
```
