### ISSUE TITLE
Worth setting query timeouts?

### ISSUE THREAD

**Issue by kevinburkeshyp** [heroku/heroku-buildpack-pgbouncer#52]
Heroku returns a 503 Server Error if a request fails to return after 30 seconds. Should `query_timeout` and other timeouts get set to a value a little higher than 30 seconds?

**Comment by kevinburkeshyp** [comment]
Whoops... realized you should probably set this with a `statement_timeout`. In any event I made the pgbouncer values configurable in a PR

**Comment by gregburek** [comment]
I attempted this as part of #29 and was met with much failure. I believe setting expert level dangerous settings should require expert level effort, or new users are likely to get in over their heads. 

Setting `statement_timeout` in the db works and should be preferred in almost all cases.
