### ISSUE TITLE
Loses settings with async workers

### ISSUE THREAD

**Issue by Koed00** [heroku/heroku-buildpack-pgbouncer#58]
I've been trying this buildpack with the various servers we run and although it runs fine with most synchronous webservers, it doesn't work well with forked processes or async workers.
The main reason for this is that forking will copy the original enviroment without the overwritten database url.
Most of my async servers have a hook to call a function just before forking though.
So my question is; Is there part of the startup script I can call that will just initialize the environment?

**Comment by gregburek** [comment]
The primary assumption of this buildpack is that everything running in the dyno is a child of the procfile command. For example, `web: bin/start-pgbouncer-stunnel bundle exec unicorn -p $PORT -c ./config/unicorn.rb -E $RACK_ENV` uses forked processes and async workers, but they inherit the environment of the parent, which is altered by the `bin/start-pgbouncer-stunnel` script. 

If you are launching a different, parallel process like `web: ./passenger-status-service-agent & bundle exec passenger start -p $PORT` I would suggest using `web: bin/start-pgbouncer-stunnel $(./passenger-status-service-agent & bundle exec passenger start -p $PORT)` or something similar to ensure the altered env is passed correctly to all children. To be fair, this strategy is a hunch and the procfile entry is completely untested. 

If this is not possible, you will need to hand spin your own env alterations as in https://github.com/heroku/heroku-buildpack-pgbouncer/blob/c1525083c2a8a2b8280ea07f82e8b461693dcf54/bin/start-pgbouncer-stunnel#L72-L78 This is very brittle and should be avoided as it bleeds assumptions and responsibilities in a bad way.
