### ISSUE TITLE
Empty passwords in DATABASE_URL will cause errors

### ISSUE THREAD

**Issue by nickcatal** [heroku/heroku-buildpack-pgbouncer#64]
Heroku's `docker-composer.yml` generator will cause `DATABASE_URL`s such as `postgres://postgres:@herokuPostgreSQL:5432/herokudb`. This buildpack will not be able to process this because there is no password.

The regex in `gen-pgbouncer-conf.sh` used to parse out the individual details needs to be updated to reflect the possibility of there not being a password.

**Comment by gregburek** [comment]
Thanks for the report. 

Why not have pgbouncer use `auth_type = trust` when the docker container is running as such?

Also, the official docker container recommends running a password:
```
         Use "-e POSTGRES_PASSWORD=password" to set
         it in "docker run".
```

Why not set that var for appropriate dev/prod parity?
