### ISSUE TITLE
pgbouncer 1.7 natively support ssl, please remove stunnel

### ISSUE THREAD

**Issue by diwu1989** [heroku/heroku-buildpack-pgbouncer#69]
I've been running just pure pgbouncer 1.7 without stunnel for a while, see fork https://github.com/BetterWorks/heroku-buildpack-pgbouncer

there's no reason to add the complexity of stunnel on top of pgbouncer now that everything is native, one less thing to fail

**Comment by gregburek** [comment]
This is being tracked in #68. 

The only blocker for me is the special TLS settings that stunnel needs to work with AWS RDS Postgres when a Heroku dyno wakes up from sleep. I need to see positive proof that either pgbouncer TLS works out of the box with RDS from a free Heroku dyno or that `option = no_ticket` is possible to pass to the underlying openssl libs from pgbouncer config.

**Comment by meskyanichi** [comment]
@gregburek using @diwu1989's fork with RDS shouldn't be an issue if you're using paid (non-idling) dynos, right?

**Comment by gregburek** [comment]
I don't know. It sounds right, but I do not know it for sure.

**Comment by thomasdavis** [comment]
@diwu1989 what is the startup command for your fork?

**Comment by thomasdavis** [comment]
`web: bin/start-pgbouncer-stunnel <command>` still?

**Comment by diwu1989** [comment]
@thomasdavis its `bin/start-pgbouncer`
https://github.com/BetterWorks/heroku-buildpack-pgbouncer/blob/master/bin/start-pgbouncer
