### ISSUE TITLE
Accessing pgBouncer Admin Console

### ISSUE THREAD

**Issue by clarencedalanjr** [heroku/heroku-buildpack-pgbouncer#71]
I have been trying to access the Admin console for pgBouncer because I need to get some statistics from pgBouncer to help in optimizing the pooling, specifically in setting the max_client_conn. Is there a way to access the Admin Console so I can use the Show commands from [here](https://pgbouncer.github.io/usage.html).

**Comment by gregburek** [comment]
Hi, so unless you can log into a running heroku dyno, this is not possible. 

You may be able to log into the stats database as a script or timed process in your app.

**Comment by clarencedalanjr** [comment]
Oh, Okay. Also just wanted to clarify something about how pgBouncer is being implemented through out the entirety of multiple dynos. Is there only a single instance of pgBouncer that handles all the incoming connection requests from lets say 2-3 dynos or are there multiple instances that handle each dyno? Also if there are multiple instances of pgBouncer running per dyno how does the pooling of connection work, does each instance owns a pool of connections or is there a shared pool that each instance can arbitrarily access?

**Comment by gregburek** [comment]
Each heroku dyno runs it's own pgbouncer and stunnel process, so concurrent database connections from that dyno are pooled. This is handy for, say a puma worker with 25 threads or sidekiq worker with 30 threads, that each need a database connection.

**Comment by clarencedalanjr** [comment]
I see, so does that mean the `PGBOUNCER_DEFAULT_POOLED_SIZE` is split per instance of the pgbouncer and stunnel process? i.e. `PGBOUNCER_DEFAULT_POOL_SIZE = 100` and there are 2 dynos will both have an instance of pgbouncer that uses DEFAULT_POOL_SIZE of 50, or is there some additional logic here?

**Comment by gregburek** [comment]
Nope, `PGBOUNCER_DEFAULT_POOL_SIZE` is the number of connections one dyno will make to the database. Run one dyno with `PGBOUNCER_DEFAULT_POOL_SIZE`=10 and you start out with 10 connections, run 10 dynos and you get 100 connections. 

All config vars and generated config are per dyno so any settings are for a given pgbouncer binary running in a dyno and pooling the db connections of that dyno.

**Comment by clarencedalanjr** [comment]
I see. Thank you for the clarification. :+1:

**Comment by kwent** [comment]
Yes it's possible to log in the admin console from the app running on your dyno.
Cf. https://github.com/kwent/pgbouncerhero-demo to see it in action.

**Comment by gregburek** [comment]
The linked app appears to assume it only runs a single web dyno and no workers. I would suggest that this configuration has other things to worry about, instead of the stats on the lone in dyno pgbouncer. 

For scaled out apps, with many web and worker dynos, the lack of other dyno visibility makes it misleading at best.
