### ISSUE TITLE
Can't connect when missing port number in DATABASE_URL

### ISSUE THREAD

**Issue by deppy** [heroku/heroku-buildpack-pgbouncer#74]
I added an RDS hosted postgres instance and in the environment variable I didn't include the port number (ie. postgress://user:pass@foobar.eu-west-1.rds.amazonaws.com/ ) and I would get the following errors:

> Apr 20 11:38:49 foobar-staging app/web.1:  OperationalError: ERROR:  No such user: u38142

Shortly after, I updated the environment variable to include the port number and then everything worked.  The behavior is that the application never connects to postgres and can be duplicated by just removing the port number from the URL that you're connecting to.

It seems as though this should be documented for non-heroku hosted instances since Heroku kindly auto-populates DATABASE_URL with the port number for us

**Comment by gregburek** [comment]
The connection string parsing for generating configs is admittedly pretty heinous https://github.com/heroku/heroku-buildpack-pgbouncer/blob/master/bin/gen-pgbouncer-conf.sh#L65

I'll about adding a note that the parser expects all parameters and will otherwise break.
