### ISSUE TITLE
Are pool settings applied across all databases or per database

### ISSUE THREAD

**Issue by mchung** [heroku/heroku-buildpack-pgbouncer#76]
I have a Postgres cluster setup with a single leader and multiple followers. We use a replica gem to distribute reads to the followers. 

Are the pool settings (PGBOUNCER_MAX_CLIENT_CONN, PGBOUNCER_DEFAULT_POOL_SIZE, etc.) applied to each database?

As an example, say PGBOUNCER_MAX_CLIENT_CONN=200, is that the total number of client connections to PgBouncer, or the total number of client connections per db, so the leader and multiple followers allow 200 each.

**Comment by gregburek** [comment]
Some pool settings are per user/database pair and some are process wide, for the pgbouncer process that is running in the dyno. 

`PGBOUNCER_MAX_CLIENT_CONN=200` will limit the total number of client connections for the pgbouncer process running in the dyno, no matter what database is being used. 

`PGBOUNCER_DEFAULT_POOL_SIZE=100` will set a default pool size for each user/database pair that pgbouncer is configured for. 

More information can be found at https://pgbouncer.github.io/config.html

**Comment by mchung** [comment]
Thanks @gregburek
