### ISSUE TITLE
How does PGBouncer work with rails?

### ISSUE THREAD

**Issue by 9mm** [heroku/heroku-buildpack-pgbouncer#82]
Hey, basic question... at a high level, how does adding `bin/start-pgbouncer-stunnel` to my Procfile before `bundle exec puma -C config/puma.rb` actually work, in terms of the database connections?

It's my understanding that Rails / Puma will use the ENV variables for database host/username/password, and just access it directly. Does PGBouncer somehow override those variables or something?

**Comment by Hengjie** [comment]
Short answer is yes.
