### ISSUE TITLE
PgBouncer 1.8.1 is out

### ISSUE THREAD

**Issue by ryanisnan** [heroku/heroku-buildpack-pgbouncer#94]
Would be nice to have this buildpack use that version.

**Comment by binarycleric** [comment]
Hello @ryanisnan. We're in the process of updating our buildpacks for the `heroku-18` stack and we plan to use pgbouncer 1.8 by then.

**Comment by ryanisnan** [comment]
Thank you very much for the update!

**Comment by binarycleric** [comment]
The latest stack image is using an up-to-date version of pgbouncer. Closing.
