### ISSUE TITLE
Using pgbouncer as a standalone?

### ISSUE THREAD

**Issue by Francescu** [heroku/heroku-buildpack-pgbouncer#97]
👋

We'd like to use `pgbouncer` to be able to connect to it from our serverless backend instead of connecting directly to the Postgres DB. 

Currently it seems that this buildpack is designed only to work with an actual Heroku web app. 

I thought I could create a dummy app to bypass that.

Would it be possible? 

Then would I be able to edit the full `.ini` config? I'd need `listen_addr`, `listen_port` and all the `auth` related settings, and they don't seem to be exposed over the `ENV` configurable settings.

**Comment by binarycleric** [comment]
Hi @Francescu. I'm not sure what you mean here. This repo is specifically for using [pgbouncer](https://pgbouncer.github.io) in a Heroku Dyno. If you need to use pgbouncer outside of a dyno then you'll need to set it up and manage it yourself.

**Comment by Francescu** [comment]
@binarycleric I wanted to setup a `pgbouncer` on a Heroku Dyno with the ability of editing more `conf.ini` fields. I ended up using another provider than Heroku but I guess it would take a PR adding more customizable fields in [gen-pgbouncer-conf.sh](https://github.com/heroku/heroku-buildpack-pgbouncer/blob/master/bin/gen-pgbouncer-conf.sh)

**Comment by Francescu** [comment]
@binarycleric 
It mainly was `listen_addr` to `*`
